In [1]:
import numpy as np

In [3]:
X = np.random.random((10, 5))
Y = np.random.random((2, 5))

In [5]:
print(X)
print(Y)

[[0.10809787 0.62418606 0.94425001 0.02348602 0.67939275]
 [0.81809091 0.25732062 0.78218482 0.60837231 0.64572891]
 [0.39087628 0.11168584 0.904963   0.35393013 0.21879399]
 [0.47513729 0.03509795 0.55176003 0.15795851 0.02355855]
 [0.80030728 0.92599993 0.80905768 0.67277658 0.80458405]
 [0.65128554 0.04547567 0.11817426 0.10475406 0.24345791]
 [0.30139082 0.57743088 0.78776876 0.24956843 0.36443893]
 [0.15290336 0.18572084 0.83140531 0.6331934  0.13581363]
 [0.36499191 0.52711073 0.71783829 0.63532759 0.45088549]
 [0.51093645 0.41546605 0.83509833 0.81880674 0.50803164]]
[[0.082425   0.79221397 0.97183693 0.0555635  0.58560256]
 [0.42214927 0.69585806 0.94205571 0.86662959 0.91947879]]


In [8]:
num_test = Y.shape[0]
num_train = X.shape[0]
dists = np.zeros((num_test, num_train))
for i in range(num_test):
    for j in range(num_train):
        #####################################################################
        # TODO:                                                             #
        # Compute the l2 distance between the ith test point and the jth    #
        # training point, and store the result in dists[i, j]. You should   #
        # not use a loop over dimension, nor use np.linalg.norm().          #
        #####################################################################
        # *****START OF YOUR CODE (DO NOT DELETE/MODIFY THIS LINE)*****
        dis = np.sqrt(np.sum((Y[i]-X[j])**2))
        dists[i, j] = dis
        

        # *****END OF YOUR CODE (DO NOT DELETE/MODIFY THIS LINE)*****
print(dists, dists.shape)

[[0.19869343 1.08281851 0.88673786 1.10918457 0.99431162 1.3150829
  0.46315242 0.9635811  0.754264   0.96582399]
 [0.93397128 0.71852584 1.04758339 1.37718195 0.5142344  1.48045259
  0.86095631 1.00677722 0.59589963 0.51915171]] (2, 10)


In [12]:
num_test = Y.shape[0]
num_train = X.shape[0]
dists_one = np.zeros((num_test, num_train))
for i in range(num_test):
    #######################################################################
    # TODO:                                                               #
    # Compute the l2 distance between the ith test point and all training #
    # points, and store the result in dists[i, :].                        #
    # Do not use np.linalg.norm().                                        #
    #######################################################################
    # *****START OF YOUR CODE (DO NOT DELETE/MODIFY THIS LINE)*****
    dis = np.sqrt(np.sum((np.expand_dims(Y[i],0).repeat(num_train,axis=0)-X)**2, axis=1))
    print(dis)
    dists_one[i, :] = dis

    # *****END OF YOUR CODE (DO NOT DELETE/MODIFY THIS LINE)*****
dists_one

[0.19869343 1.08281851 0.88673786 1.10918457 0.99431162 1.3150829
 0.46315242 0.9635811  0.754264   0.96582399]
[0.93397128 0.71852584 1.04758339 1.37718195 0.5142344  1.48045259
 0.86095631 1.00677722 0.59589963 0.51915171]


array([[0.19869343, 1.08281851, 0.88673786, 1.10918457, 0.99431162,
        1.3150829 , 0.46315242, 0.9635811 , 0.754264  , 0.96582399],
       [0.93397128, 0.71852584, 1.04758339, 1.37718195, 0.5142344 ,
        1.48045259, 0.86095631, 1.00677722, 0.59589963, 0.51915171]])

In [13]:
num_test = Y.shape[0]
num_train = X.shape[0]
dists_one = np.zeros((num_test, num_train))

Y = Y.reshape(num_test,1,-1)
X = X.reshape(1,num_train,-1)
print(Y.shape,X.shape)

(2, 1, 5) (1, 10, 5)


In [18]:
dists = np.sqrt(np.sum((X - Y)**2,axis=2))
print(dists.shape)
print(dists)

(2, 10)
[[0.19869343 1.08281851 0.88673786 1.10918457 0.99431162 1.3150829
  0.46315242 0.9635811  0.754264   0.96582399]
 [0.93397128 0.71852584 1.04758339 1.37718195 0.5142344  1.48045259
  0.86095631 1.00677722 0.59589963 0.51915171]]
